package dev.soundceiling.app;
import java.util.Arrays;
public final class PureLogicTest{
 public static void main(String[]a){testOutput();testPeak();testCurve();testDecision();testFrequency();testState();testLog();testDestination();testSafetyGuard();testManualOverride();testWriteTracker();testFirstBlockPeakGuard();testTransientGuard();testLoudnessMeter();testNormalizationPresets();testProfiles();System.out.println("PureLogicTest: PASS");}
 static void testOutput(){assertFalse(Arrays.stream(OutputDevicePriority.forSdk(29)).anyMatch(v->v==26),"API29 BLE");}
 static void testPeak(){assertNear(-4f,GainPlanner.dbfs(-20f,-2f,0f,-10f,-6f,true,1f).desiredGainDb,.001f,"ceiling");}
 static void testCurve(){VolumeCurveMath.ValidationResult r=VolumeCurveMath.validate(new float[16],0,15);assertTrue(r.fallbackUsed,"flat fallback");assertEquals("flat_or_single_finite",r.reason,"reason");ControlVolumeCurve c=new ControlVolumeCurve(0,15);assertEquals(5,c.capIndexFromPercent(35),"cap");}
 static void testDecision(){ControlVolumeCurve c=new ControlVolumeCurve(0,15);ControlDecision d=DecisionEngine.decide(DecisionEngine.Input.dbfs(10000,-13.9f,-3.7f,true,0,-18f,-3f,true,1f,35,false,SpeedPreset.BALANCED,0,0,0),c);assertEquals(5,d.rawDesiredIndex,"raw");assertTrue(d.requestedIndex>=1,"audible");assertTrue(d.safetyReason==ControlDecision.SafetyReason.AUDIBLE_FLOOR,"floor");}
 static void testFrequency(){float[] centers=FrequencyBandTracker.centerFrequencies();for(int w=0;w<centers.length;w++){short[] pcm=ToneSamples.sinePcm16(48000,500,centers[w],-6f,2);float[] l=new FrequencyBandTracker(48000,2).update(pcm,pcm.length);int strongest=0;for(int i=1;i<l.length;i++)if(l[i]>l[strongest])strongest=i;assertEquals(w,strongest,"band");}}
 static void testState(){float[] b={1,.8f,.6f,.4f,.2f};RuntimeState s=new RuntimeState.Builder().running(true).captureStatus(RuntimeState.CaptureStatus.RUNNING).controlActivity(RuntimeState.ControlActivity.MINIMUM_LIMIT).signalPresent(true).volume(1,15).bandLevels(b).message("Работает").build();b[0]=0;assertNear(1,s.bandLevels()[0],.001f,"copy");assertEquals("Media 1/15",StatusText.media(s),"media");}
 static void testLog(){ControlDecision d=DecisionEngine.decide(DecisionEngine.Input.dbfs(12345,-13.9f,-3.7f,true,0,-18f,-3f,true,1f,35,false,SpeedPreset.BALANCED,0,0,0),new ControlVolumeCurve(0,15)).withAppliedIndex(1);String l=LogFormatter.formatDecision(d);assertTrue(l.contains("raw=5"),"raw log");assertFalse(l.toLowerCase().contains("pcm"),"no pcm");}
 static void testDestination(){assertTrue(AppDestination.fromPreference("broken")==AppDestination.SIMPLE,"fallback");}
 static void testSafetyGuard(){SafetySettings s=new SafetySettings(1,10,true,6,1,750);assertEquals(6,SafetyGuard.clampRequested(15,s,10),"safety lock final");assertEquals(4,SafetyGuard.clampRequested(4,s,5),"normal request preserved");SafetySettings malformed=new SafetySettings(8,3,false,15,1,750);assertTrue(malformed.minIndex<=malformed.maxIndex,"normalized range");}
 static void testManualOverride(){ManualSafetyController c=new ManualSafetyController(1,10,750);c.observeUserIndex(5,1000);c.observeUserIndex(4,1100);assertTrue(c.isPausedForRaise(),"one-step user decrease pauses raise");assertEquals(4,c.effectiveMax(),"one-step shrinks envelope");c.observeUserIndex(1,1200);assertTrue(c.isManualSafetyPause(),"minimum enters safety pause");c.observeUserIndex(2,2000);assertTrue(c.isPausedForRaise(),"manual raise begins gradual recovery");assertEquals(2,c.effectiveMax(),"manual raise does not jump envelope");c.tick(2750);assertEquals(3,c.effectiveMax(),"gradual recovery one step");}
 static void testWriteTracker(){VolumeWriteTracker t=new VolumeWriteTracker(250);t.observeInitial(3);t.noteAppWrite(2,1000);assertTrue(t.classifyObserved(2,1100)==VolumeWriteTracker.Origin.APP,"app write ack");assertTrue(t.classifyObserved(3,1200)==VolumeWriteTracker.Origin.USER,"one-step user change");assertTrue(t.classifyObserved(3,1250)==VolumeWriteTracker.Origin.UNCHANGED,"unchanged");}
 static void testFirstBlockPeakGuard(){ControlVolumeCurve c=new ControlVolumeCurve(0,15);int safe=PeakSafetyDetector.safeTargetForSourcePeak(-0.5f,5,c,-2f,1,10);assertEquals(4,safe,"first-block hot peak lowers immediately");int unchanged=PeakSafetyDetector.safeTargetForSourcePeak(-6f,5,c,-2f,1,10);assertEquals(5,unchanged,"safe peak unchanged");LoudnessTracker.Reading r=new LoudnessTracker().update(.25,-.5f,.05);assertNear(-.5f,r.rawBlockPeakDb,.001f,"raw peak exposed before smoother");}
 static void testTransientGuard(){TransientGuard g=new TransientGuard(6f,10f);g.update(0,-20f);g.update(50,-20f);TransientGuard.Event warning=g.update(100,-13.5f);assertTrue(warning.severity==TransientGuard.Severity.WARNING,"+6 dB warning");assertTrue(warning.deltaDb>6f,"warning delta");TransientGuard h=new TransientGuard(6f,10f);h.update(0,-20f);TransientGuard.Event emergency=h.update(50,-9.5f);assertTrue(emergency.severity==TransientGuard.Severity.EMERGENCY,"+10 dB emergency");}
 static void testLoudnessMeter(){short[] quiet=ToneSamples.sinePcm16(48000,1000,1000f,-24f,2);short[] loud=ToneSamples.sinePcm16(48000,1000,1000f,-12f,2);LoudnessMeter q=new LoudnessMeter(48000,2);LoudnessMeter.Reading qr=q.update(quiet,quiet.length);LoudnessMeter l=new LoudnessMeter(48000,2);LoudnessMeter.Reading lr=l.update(loud,loud.length);assertTrue(Float.isFinite(qr.lufsLike),"quiet finite");assertTrue(lr.lufsLike>qr.lufsLike+10f,"12 dB input difference preserved");LoudnessMeter silence=new LoudnessMeter(48000,2);LoudnessMeter.Reading sr=silence.update(new short[4800],4800);assertTrue(sr.lufsLike<=-80f,"silence low");}
 static void testNormalizationPresets(){assertEquals(1,ControlDefaults.MIN_MEDIA_INDEX,"default min");assertEquals(70,ControlDefaults.MAX_MEDIA_PERCENT,"default max");assertNear(-20f,NormalizationPreset.LIGHT.targetLoudness,.001f,"light target");assertNear(.35f,NormalizationPreset.LIGHT.strength,.001f,"light strength");assertEquals(120,NormalizationPreset.LIGHT.downwardAttackMs,"light attack");assertNear(-18f,NormalizationPreset.MEDIUM.targetLoudness,.001f,"medium target");assertNear(2.5f,NormalizationPreset.MEDIUM.toleranceLu,.001f,"medium tolerance");assertEquals(80,NormalizationPreset.MEDIUM.downwardAttackMs,"medium attack");assertEquals(1500,NormalizationPreset.MEDIUM.upwardReleaseMs,"medium release");assertNear(1f,NormalizationPreset.STRICT.strength,.001f,"strict strength");assertEquals(3,NormalizationPreset.STRICT.maxDownSteps,"strict down steps");assertFalse(NormalizationPreset.OFF.allowsLoudnessRaise(),"off no loudness raise");GainPlanner.Plan p=GainPlanner.loudness(-24f,-3f,-10f,-18f,-2f,true,.65f);assertTrue(p.desiredGainDb>-10f,"quiet loudness requests gain");}
 static void testProfiles(){ControlProfile balanced=BuiltInProfiles.balanced();assertEquals(1,balanced.minMediaIndex,"balanced min");assertEquals(70,balanced.maxMediaPercent,"balanced max");assertTrue(balanced.normalizationPreset==NormalizationPreset.MEDIUM,"balanced medium");ControlProfile safe=BuiltInProfiles.safe();assertEquals(40,safe.maxMediaPercent,"safe max");assertTrue(safe.safetyLockEnabled,"safe lock");assertEquals(40,safe.safetyLockPercent,"safe lock max");ControlProfile stable=BuiltInProfiles.stableLoudness();assertTrue(stable.normalizationPreset==NormalizationPreset.STRICT,"stable strict");ControlProfile movie=BuiltInProfiles.movieDynamic();assertTrue(movie.normalizationPreset==NormalizationPreset.LIGHT,"movie light");ControlProfile speech=BuiltInProfiles.speech();assertNear(-19f,speech.targetLoudness,.001f,"speech target");String encoded=safe.encode();ControlProfile decoded=ControlProfile.decode(encoded);assertTrue(safe.sameSettings(decoded),"profile round trip");ControlProfile modified=decoded.withMaxMediaPercent(41);assertFalse(safe.sameSettings(modified),"modified detected");}
 static void assertTrue(boolean v,String m){if(!v)throw new AssertionError(m);}static void assertFalse(boolean v,String m){assertTrue(!v,m);}static void assertNear(float e,float a,float x,String m){if(Math.abs(e-a)>x)throw new AssertionError(m+":"+a);}static void assertEquals(int e,int a,String m){if(e!=a)throw new AssertionError(m+":"+a);}static void assertEquals(String e,String a,String m){if(!e.equals(a))throw new AssertionError(m+":"+a);}
}
