package dev.soundceiling.app;

final class DecisionEngine {
    static final class Input {
        final long nowMs;final ControlDecision.Mode mode;final float sourceRmsDb,sourcePeakDb;final boolean signalPresent;final int currentIndex;final float currentMeasurementGainDb,calibrationOffsetDb,target,ceiling;final boolean normalize;final float strength;final int maxVolumePercent;final boolean allowAutoMute;final SpeedPreset speed;final long lastRaiseAtMs,lastDecreaseAtMs,loudHoldUntilMs;
        private Input(long nowMs,ControlDecision.Mode mode,float rms,float peak,boolean signal,int current,float measured,float offset,float target,float ceiling,boolean normalize,float strength,int maxPercent,boolean allow,SpeedPreset speed,long raise,long decrease,long hold){this.nowMs=nowMs;this.mode=mode;sourceRmsDb=rms;sourcePeakDb=peak;signalPresent=signal;currentIndex=current;currentMeasurementGainDb=measured;calibrationOffsetDb=offset;this.target=target;this.ceiling=ceiling;this.normalize=normalize;this.strength=strength;maxVolumePercent=maxPercent;allowAutoMute=allow;this.speed=speed;lastRaiseAtMs=raise;lastDecreaseAtMs=decrease;loudHoldUntilMs=hold;}
        static Input dbfs(long now,float rms,float peak,boolean signal,int current,float target,float ceiling,boolean normalize,float strength,int max,boolean allow,SpeedPreset speed,long raise,long decrease,long hold){return new Input(now,ControlDecision.Mode.DBFS,rms,peak,signal,current,0,0,target,ceiling,normalize,strength,max,allow,speed,raise,decrease,hold);}
        static Input spl(long now,float rms,float peak,boolean signal,int current,float measured,float offset,float target,float ceiling,boolean normalize,float strength,int max,boolean allow,SpeedPreset speed,long raise,long decrease,long hold){return new Input(now,ControlDecision.Mode.SPL,rms,peak,signal,current,measured,offset,target,ceiling,normalize,strength,max,allow,speed,raise,decrease,hold);}
    }
    static ControlDecision decide(Input in,ControlVolumeCurve curve){int cap=curve.capIndexFromPercent(in.maxVolumePercent);int current=DbMath.clamp(in.currentIndex,curve.minIndex(),curve.maxIndex());float gain=curve.gainDbForIndex(current);if(current>cap)return make(in,gain,cap,gain,current,cap,false,ControlDecision.Action.CAP,ControlDecision.SafetyReason.MAXIMUM_CAP,"maximum_cap",cap);if(!in.signalPresent)return make(in,gain,cap,gain,current,current,false,ControlDecision.Action.HOLD,ControlDecision.SafetyReason.NONE,"no_signal",current);GainPlanner.Plan plan=in.mode==ControlDecision.Mode.DBFS?GainPlanner.dbfs(in.sourceRmsDb,in.sourcePeakDb,gain,in.target,in.ceiling,in.normalize,in.strength):GainPlanner.splFromEstimate(in.sourceRmsDb,in.sourcePeakDb,gain,in.currentMeasurementGainDb,in.calibrationOffsetDb,in.target,in.ceiling,in.normalize,in.strength);int raw=curve.bestIndexAtOrBelowGain(plan.desiredGainDb,cap);boolean peak=plan.projectedPeak>plan.ceiling+.15f;if(Math.abs(plan.desiredGainDb-gain)<.8f&&!peak)raw=current;AudibleFloorPolicy.Result safe=AudibleFloorPolicy.apply(raw,curve.minIndex(),cap,true,in.allowAutoMute);int target=safe.index;ControlDecision.SafetyReason safety=safe.reason;String reason="at_target";ControlDecision.Action action=ControlDecision.Action.HOLD;int requested=current;if(current==curve.minIndex()&&!in.allowAutoMute&&target>current){requested=Math.min(curve.minIndex()+1,cap);safety=ControlDecision.SafetyReason.AUDIBLE_FLOOR;action=ControlDecision.Action.RAISE;reason="audible_floor_recovery";}else if(target<current&&peak){requested=target;action=ControlDecision.Action.DECREASE;reason="peak_emergency";}else if(target<current&&in.nowMs-in.lastDecreaseAtMs>=in.speed.decreaseIntervalMs){requested=Math.max(target,current-in.speed.maxDecreaseStep);action=ControlDecision.Action.DECREASE;reason="decrease_step";}else if(in.normalize&&target>current&&in.nowMs>=in.loudHoldUntilMs&&in.nowMs-in.lastRaiseAtMs>=in.speed.raiseIntervalMs){requested=Math.min(target,current+in.speed.maxRaiseStep);action=ControlDecision.Action.RAISE;reason="raise_step";}else if(target!=current)reason="rate_limited";return make(in,gain,cap,plan.desiredGainDb,raw,target,peak,action,safety,reason,requested);}
    private static ControlDecision make(Input i,float gain,int cap,float desired,int raw,int protectedIndex,boolean peak,ControlDecision.Action action,ControlDecision.SafetyReason safety,String reason,int requested){return new ControlDecision(i.nowMs,i.mode,i.sourceRmsDb,i.sourcePeakDb,i.signalPresent,i.allowAutoMute,i.currentIndex,gain,i.target,i.ceiling,i.maxVolumePercent,cap,desired,raw,protectedIndex,peak,action,safety,reason,requested,i.currentIndex);}
    private DecisionEngine(){}
}
