from pathlib import Path

def rep(path, old, new, label):
    p = Path(path)
    s = p.read_text()
    if new in s:
        return
    if old not in s:
        raise SystemExit(label + ": anchor missing")
    p.write_text(s.replace(old, new, 1))

service = "app/src/main/java/dev/soundceiling/app/NormalizerService.java"
rep(service,
'        if (command.kind() == ControlCommand.Kind.DSP_GAIN) {\n            boolean applied = optionalDsp != null && optionalDsp.applyGain(\n                    command.requestedGainDb(), isSafetyCommand(command));\n            DiagnosticLog.transition("dsp_gain_command", command.reason(),\n                    "requestedGainDb=" + command.requestedGainDb() + " applied=" + applied);\n            return current;\n        }\n',
'        if (command.kind() == ControlCommand.Kind.DSP_GAIN) {\n            int sessionBefore = optionalDsp == null ? -1 : optionalDsp.enhancedSessionId();\n            boolean applied = optionalDsp != null && optionalDsp.applyGain(\n                    command.requestedGainDb(), isSafetyCommand(command));\n            float appliedGainDb = optionalDsp == null ? 0f : optionalDsp.appliedGainDb();\n            DiagnosticLog.transition("dsp_gain_command", command.reason(),\n                    "requestedGainDb=" + command.requestedGainDb() + " applied=" + applied);\n            if (sessionBefore > 0) {\n                DiagnosticLog.transition("session_dsp_apply",\n                        sessionBefore + ":" + command.requestedGainDb() + ":" + applied,\n                        "session=" + sessionBefore + " requestedGainDb="\n                                + command.requestedGainDb() + " appliedGainDb=" + appliedGainDb\n                                + " applied=" + applied + " media=" + current);\n                if (!applied && enhancedSessionDsp != null) {\n                    enhancedSessionDsp.onApplyFailed("session_dsp_apply_failed");\n                }\n            }\n            return current;\n        }\n', "service DSP apply")

rep(service,
'                .profileName(currentProfileV2 != null ? currentProfileV2.name\n                        : currentProfile == null ? "" : currentProfile.name)\n                .logStatus(logger == null ? "" : logger.status())\n                .unexpectedZero(unexpectedZeroThisPoll);\n',
'                .profileName(currentProfileV2 != null ? currentProfileV2.name\n                        : currentProfile == null ? "" : currentProfile.name)\n                .logStatus(logger == null ? "" : logger.status())\n                .enhancedSession(enhancedSessionDsp != null && enhancedSessionDsp.permissionGranted(),\n                        enhancedSessionDsp != null && enhancedSessionDsp.active(),\n                        enhancedSessionDsp == null ? -1 : enhancedSessionDsp.sessionId(),\n                        enhancedSessionDsp == null ? -1 : enhancedSessionDsp.sessionUid(),\n                        enhancedSessionDsp == null ? "" : enhancedSessionDsp.sessionPackage(),\n                        controlCoordinator.snapshot().desiredGainDb(),\n                        optionalDsp == null ? 0f : optionalDsp.appliedGainDb(),\n                        enhancedSessionDsp == null ? "session_runtime_missing" : enhancedSessionDsp.reason())\n                .unexpectedZero(unexpectedZeroThisPoll);\n', "service telemetry")

simple = "app/src/main/java/dev/soundceiling/app/SimpleModeView.java"
rep(simple,
'import android.content.Context;\nimport android.content.Intent;\nimport android.provider.Settings;\n',
'import android.content.ClipData;\nimport android.content.ClipboardManager;\nimport android.content.Context;\nimport android.content.Intent;\nimport android.content.pm.PackageManager;\nimport android.provider.Settings;\n', "simple imports")
rep(simple,
'    private final TextView globalStatus, linkedHint, lowerLabel, upperLabel, safetyLabel, normalizeLabel;\n    private final SeekBar lowerSeek, upperSeek, safetySeek;\n    private final Button startStop;\n    private final Button sourceAccess;\n',
'    private final TextView globalStatus, linkedHint, lowerLabel, upperLabel, safetyLabel, normalizeLabel;\n    private final TextView sessionDspSetupStatus;\n    private final SeekBar lowerSeek, upperSeek, safetySeek;\n    private final Button startStop;\n    private final Button sourceAccess;\n    private final Button copySessionDspCommand;\n', "simple fields")
rep(simple,
'        root.addView(statusCard, statusLp);\n\n        sourceAccess = new Button(context);\n',
'        root.addView(statusCard, statusLp);\n\n        sessionDspSetupStatus = secondary("", 13);\n        sessionDspSetupStatus.setPadding(0, dp(2), 0, dp(6));\n        root.addView(sessionDspSetupStatus);\n        copySessionDspCommand = new Button(context);\n        copySessionDspCommand.setAllCaps(false);\n        copySessionDspCommand.setText("Копировать команду Enhanced Session DSP");\n        copySessionDspCommand.setOnClickListener(v -> copyEnhancedSessionCommand());\n        LinearLayout.LayoutParams setupLp = new LinearLayout.LayoutParams(LayoutParams.MATCH_PARENT, dp(50));\n        setupLp.bottomMargin = dp(8);\n        root.addView(copySessionDspCommand, setupLp);\n\n        sourceAccess = new Button(context);\n', "simple setup block")
rep(simple,
'    private SimpleModeModel model() {\n        boolean active = runtime.dspTransportCapability\n                == EngineCapabilities.DspTransportCapability.VERIFIED_GLOBAL_MIX;\n        return new SimpleModeModel(Prefs.outputCeilings(getContext()), curve, active,\n                Prefs.globalDspEnabled(getContext()), active);\n    }\n',
'    private SimpleModeModel model() {\n        boolean verified = runtime.sessionDspActive\n                || runtime.dspTransportCapability == EngineCapabilities.DspTransportCapability.VERIFIED_POLICY_SCOPED\n                || runtime.dspTransportCapability == EngineCapabilities.DspTransportCapability.VERIFIED_GLOBAL_MIX;\n        boolean globalMixActive = runtime.dspTransportCapability\n                == EngineCapabilities.DspTransportCapability.VERIFIED_GLOBAL_MIX;\n        return new SimpleModeModel(Prefs.outputCeilings(getContext()), curve, verified,\n                Prefs.globalDspEnabled(getContext()), globalMixActive);\n    }\n', "simple model")
rep(simple,
'        sourceAccess.setVisibility(runtime.sourceAccessState == CaptureRequestCoordinator.SourceAccessState.ACCESS_MISSING\n                ? View.VISIBLE : View.GONE);\n        refreshSharedControls();\n',
'        sourceAccess.setVisibility(runtime.sourceAccessState == CaptureRequestCoordinator.SourceAccessState.ACCESS_MISSING\n                ? View.VISIBLE : View.GONE);\n        refreshEnhancedSessionSetup();\n        refreshSharedControls();\n', "simple render")
rep(simple,
'    private void updateSafetyLabel(int percent) {\n',
'    private void refreshEnhancedSessionSetup() {\n        boolean granted = getContext().checkSelfPermission(EnhancedSessionSetup.DUMP_PERMISSION)\n                == PackageManager.PERMISSION_GRANTED;\n        if (!granted) {\n            sessionDspSetupStatus.setText(EnhancedSessionSetup.REQUIRED_STATUS + "\\n"\n                    + EnhancedSessionSetup.ADB_GRANT_COMMAND);\n            copySessionDspCommand.setVisibility(View.VISIBLE);\n            return;\n        }\n        copySessionDspCommand.setVisibility(View.GONE);\n        sessionDspSetupStatus.setText(runtime.running ? StatusText.sessionDsp(runtime)\n                : "Enhanced Session DSP permission granted · session discovery starts with playback");\n    }\n\n    private void copyEnhancedSessionCommand() {\n        ClipboardManager clipboard = (ClipboardManager) getContext().getSystemService(Context.CLIPBOARD_SERVICE);\n        if (clipboard != null) clipboard.setPrimaryClip(ClipData.newPlainText(\n                "SoundCeiling Enhanced Session DSP", EnhancedSessionSetup.ADB_GRANT_COMMAND));\n    }\n\n    private void updateSafetyLabel(int percent) {\n', "simple methods")

adv = "app/src/main/java/dev/soundceiling/app/AdvancedModeView.java"
rep(adv,
'import android.app.AlertDialog;\nimport android.content.Context;\nimport android.graphics.Typeface;\n',
'import android.app.AlertDialog;\nimport android.content.ClipData;\nimport android.content.ClipboardManager;\nimport android.content.Context;\nimport android.content.pm.PackageManager;\nimport android.graphics.Typeface;\n', "advanced imports")
rep(adv,
'    private final TextView modeInfo, profileInfo, liveDetails, decisionDetails, globalDspStatus, linkedLockHint;\n    private final Button startStop;\n',
'    private final TextView modeInfo, profileInfo, liveDetails, decisionDetails, globalDspStatus, linkedLockHint;\n    private final TextView sessionDspSetupStatus;\n    private final Button copySessionDspCommand;\n    private final Button startStop;\n', "advanced fields")
rep(adv,
'        statusCard = new StatusCardView(context); root.addView(statusCard,\n                new LinearLayout.LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.WRAP_CONTENT));\n\n        section("Основной actuator");\n',
'        statusCard = new StatusCardView(context); root.addView(statusCard,\n                new LinearLayout.LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.WRAP_CONTENT));\n\n        sessionDspSetupStatus = secondary("", 13);\n        sessionDspSetupStatus.setPadding(0, dp(8), 0, dp(6));\n        root.addView(sessionDspSetupStatus);\n        copySessionDspCommand = button("Копировать команду Enhanced Session DSP");\n        copySessionDspCommand.setOnClickListener(v -> copyEnhancedSessionCommand());\n        root.addView(copySessionDspCommand, fullButton());\n\n        section("Основной actuator");\n', "advanced setup block")
rep(adv,
'        startStop.setText(runtime.running ? "Остановить" : "Запустить"); statusCard.render(runtime); frequencyMeter.renderState(runtime);\n        refreshSharedOutputControls();\n',
'        startStop.setText(runtime.running ? "Остановить" : "Запустить"); statusCard.render(runtime); frequencyMeter.renderState(runtime);\n        refreshEnhancedSessionSetup();\n        refreshSharedOutputControls();\n', "advanced render")
rep(adv,
'    private SimpleModeModel outputModel() {\n        boolean active = runtime.dspTransportCapability\n                == EngineCapabilities.DspTransportCapability.VERIFIED_GLOBAL_MIX;\n        return new SimpleModeModel(Prefs.outputCeilings(getContext()),\n                new ControlVolumeCurve(streamMin, streamMax), active,\n                Prefs.globalDspEnabled(getContext()), active);\n    }\n',
'    private SimpleModeModel outputModel() {\n        boolean verified = runtime.sessionDspActive\n                || runtime.dspTransportCapability == EngineCapabilities.DspTransportCapability.VERIFIED_POLICY_SCOPED\n                || runtime.dspTransportCapability == EngineCapabilities.DspTransportCapability.VERIFIED_GLOBAL_MIX;\n        boolean globalMixActive = runtime.dspTransportCapability\n                == EngineCapabilities.DspTransportCapability.VERIFIED_GLOBAL_MIX;\n        return new SimpleModeModel(Prefs.outputCeilings(getContext()),\n                new ControlVolumeCurve(streamMin, streamMax), verified,\n                Prefs.globalDspEnabled(getContext()), globalMixActive);\n    }\n', "advanced model")
rep(adv,
'    private void refreshSharedOutputControls() {\n',
'    private void refreshEnhancedSessionSetup() {\n        boolean granted = getContext().checkSelfPermission(EnhancedSessionSetup.DUMP_PERMISSION)\n                == PackageManager.PERMISSION_GRANTED;\n        if (!granted) {\n            sessionDspSetupStatus.setText(EnhancedSessionSetup.REQUIRED_STATUS + "\\n"\n                    + EnhancedSessionSetup.ADB_GRANT_COMMAND);\n            copySessionDspCommand.setVisibility(View.VISIBLE);\n            return;\n        }\n        copySessionDspCommand.setVisibility(View.GONE);\n        sessionDspSetupStatus.setText(runtime.running ? StatusText.sessionDsp(runtime)\n                : "Enhanced Session DSP permission granted · session discovery starts with playback");\n    }\n\n    private void copyEnhancedSessionCommand() {\n        ClipboardManager clipboard = (ClipboardManager) getContext().getSystemService(Context.CLIPBOARD_SERVICE);\n        if (clipboard != null) clipboard.setPrimaryClip(ClipData.newPlainText(\n                "SoundCeiling Enhanced Session DSP", EnhancedSessionSetup.ADB_GRANT_COMMAND));\n    }\n\n    private void refreshSharedOutputControls() {\n', "advanced methods")
