#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PKG="$ROOT/app/src/main/java/dev/soundceiling/app"
require(){ local file="$1"; local needle="$2"; [[ -f "$file" ]] || { echo "Missing v0.5 UI file: $(basename "$file")" >&2; exit 1; }; grep -Fq -- "$needle" "$file" || { echo "Missing v0.5 UI contract: $(basename "$file") -> $needle" >&2; exit 1; }; }
reject(){ local file="$1"; local needle="$2"; if [[ -f "$file" ]] && grep -Fq -- "$needle" "$file"; then echo "Obsolete UI status survived: $(basename "$file") -> $needle" >&2; exit 1; fi; }

# Task 12: per-app and system-stream policy UI.
require "$PKG/AppDestination.java" "APPS_SYSTEM"
require "$PKG/DrawerLayoutController.java" "Приложения и системные звуки"
require "$PKG/MainActivity.java" "AppsSystemView"
require "$PKG/AppsSystemView.java" "Поиск приложений"
require "$PKG/AppsSystemView.java" "Controlled"
require "$PKG/AppsSystemView.java" "Custom"
require "$PKG/AppsSystemView.java" "Ignored"
require "$PKG/AppsSystemView.java" "PCM unavailable"
require "$PKG/AppsSystemView.java" "System apps"
require "$PKG/AppPolicyEditorView.java" "Global"
require "$PKG/AppPolicyEditorView.java" "On"
require "$PKG/AppPolicyEditorView.java" "Off"
require "$PKG/AppPolicyEditorView.java" "Custom"
require "$PKG/AppsSystemView.java" "Calls"
require "$PKG/AppsSystemView.java" "Alarm"
require "$PKG/AppsSystemView.java" "Ringtone"
require "$PKG/AppsSystemView.java" "Notifications"
require "$PKG/AppsSystemView.java" "System"
require "$PKG/AppsSystemView.java" "DTMF"
require "$PKG/AppsSystemView.java" "Accessibility"
require "$PKG/AppsSystemView.java" "Assistant"
require "$PKG/AppsSystemView.java" "ceilingPercent"

# Task 13: Device Profiles 2.0 and truthful hybrid-engine status surfaces.
# v0.7 preserves the status architecture while replacing implementation-shaped v0.5 labels
# with user-facing capability levels. Raw capabilities remain visible in diagnostics.
require "$PKG/AppDestination.java" "DEVICE_PROFILES"
require "$PKG/DrawerLayoutController.java" "Профили устройств"
require "$PKG/MainActivity.java" "DeviceProfilesView"
require "$PKG/DeviceProfilesView.java" "Активный аудиовыход"
require "$PKG/DeviceProfilesView.java" "Калибровка"
require "$PKG/DeviceProfilesView.java" "Media ceiling"
require "$PKG/DeviceProfilesView.java" "Fallback ceiling"
require "$PKG/DeviceProfilesView.java" "App overrides"
require "$PKG/SimpleModeView.java" "StatusCardView"
require "$PKG/StatusText.java" "Precise PCM"
require "$PKG/StatusText.java" "Safe fallback"
require "$PKG/StatusText.java" "System-only protection"
require "$PKG/StatusText.java" "Recovery:"
require "$PKG/StatusText.java" "SoundCeiling"
reject "$PKG/StatusText.java" "Smart PCM"
reject "$PKG/StatusText.java" "System limiter only"
reject "$PKG/StatusText.java" "DSP active"
reject "$PKG/StatusText.java" "Mixed apps · shared down-only control"
reject "$PKG/StatusText.java" "Source uncertain · Global down-only control"
require "$PKG/AdvancedModeView.java" "StatusCardView"
require "$PKG/StatusCardView.java" "Source confidence"
require "$PKG/StatusCardView.java" "Metering capability"
require "$PKG/StatusCardView.java" "Volume control capability"
require "$PKG/StatusCardView.java" "DSP capability"
require "$PKG/DiagnosticsView.java" "sourceConfidence"
require "$PKG/DiagnosticsView.java" "meteringCapability"
require "$PKG/DiagnosticsView.java" "volumeControlCapability"
require "$PKG/DiagnosticsView.java" "dspTransportCapability"

echo "v0.5/v0.7 UI compatibility contract: PASS"
