#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PKG="$ROOT/app/src/main/java/dev/soundceiling/app"
require(){ local file="$1"; local needle="$2"; grep -Fq "$needle" "$file" || { echo "Missing v0.4 UI contract: $(basename "$file") -> $needle" >&2; exit 1; }; }
# Preserve the v0.4 surfaces while allowing later releases' clearer names.
require "$PKG/SimpleModeView.java" "Минимальный потолок выхода"
require "$PKG/SimpleModeView.java" "Максимальный потолок выхода"
# v0.7.1 Task 9 intentionally removes Quiet Now from Simple; Advanced retains it.
require "$PKG/AdvancedModeView.java" "Quiet Now"
require "$PKG/SimpleModeView.java" "Normalization:"
require "$PKG/AdvancedModeView.java" "Safety Lock"
require "$PKG/AdvancedModeView.java" "Peak и transient protection"
require "$PKG/AdvancedModeView.java" "Normalization strength"
# v0.7 renamed the old generic Behavior heading. Preserve the actual controls instead of pinning copy.
require "$PKG/AdvancedModeView.java" "Downward attack"
require "$PKG/AdvancedModeView.java" "Hold after loud"
require "$PKG/AdvancedModeView.java" "Живые показатели"
require "$PKG/AdvancedModeView.java" "Профили"
require "$PKG/AdvancedModeView.java" "По умолчанию"
require "$PKG/HelpText.java" "MIN_MEDIA"
require "$PKG/HelpText.java" "SOURCE_PEAK"
require "$PKG/HelpText.java" "NORMALIZATION_STRENGTH"
require "$PKG/AppDestination.java" "EQ"
require "$PKG/AppDestination.java" "DIAGNOSTICS"
require "$PKG/AppDestination.java" "APPEARANCE"
require "$PKG/EqView.java" "Эквалайзер"
require "$PKG/EqView.java" "отдельный модуль"
require "$PKG/DiagnosticsView.java" "Диагностика"
require "$PKG/DiagnosticsView.java" "GREEN"
require "$PKG/DiagnosticsView.java" "YELLOW"
require "$PKG/DiagnosticsView.java" "RED"
require "$PKG/AppearanceView.java" "Системная"
require "$PKG/AppearanceView.java" "Тёмная"
require "$PKG/AppearanceView.java" "Светлая"
require "$PKG/CalibrationView.java" "У меня нет SPL-метра"
echo "v0.4 UI contract: PASS"
