package dev.soundceiling.app;
public final class V072MediaAnchorPureTest {
 public static void main(String[] args){appDropDoesNotMoveUserAnchor();unknownSourceMayRepayDebtButNotRaiseAboveAnchor();userWriteRebasesAnchorAndCancelsFightLoop();quietNowDoesNotCreateRecoverableDebt();userAuthorityHoldBlocksImmediateOrdinaryCounterWrite();coordinatorRepaysOwnedDebtWithUnknownSource();System.out.println("V072MediaAnchorPureTest: PASS");}
 private static void appDropDoesNotMoveUserAnchor(){MediaAnchorState s=MediaAnchorState.start(5,0).recordAppWrite(5,4,VolumeWriteOrigin.NORMALIZATION).recordAppWrite(4,3,VolumeWriteOrigin.NORMALIZATION);eq(5,s.userAnchorIndex(),"anchor");eq(2,s.debtSteps(),"debt");eq(5,s.maxDebtRecoveryIndex(),"recover");}
 private static void unknownSourceMayRepayDebtButNotRaiseAboveAnchor(){MediaAnchorState s=MediaAnchorState.start(5,0).recordAppWrite(5,4,VolumeWriteOrigin.NORMALIZATION).recordAppWrite(4,3,VolumeWriteOrigin.HARD_PEAK_SAFETY);yes(s.mayRecoverTo(4),"4");yes(s.mayRecoverTo(5),"5");no(s.mayRecoverTo(6),"6");}
 private static void userWriteRebasesAnchorAndCancelsFightLoop(){MediaAnchorState s=MediaAnchorState.start(2,0).recordAppWrite(2,1,VolumeWriteOrigin.NORMALIZATION).recordUserIndex(2,100);eq(2,s.userAnchorIndex(),"user anchor");eq(0,s.debtSteps(),"cleared debt");yes(s.userAuthorityHoldActive(300),"hold");}
 private static void quietNowDoesNotCreateRecoverableDebt(){MediaAnchorState s=MediaAnchorState.start(5,0).recordAppWrite(5,1,VolumeWriteOrigin.QUIET_NOW);eq(0,s.debtSteps(),"quiet debt");eq(1,s.maxDebtRecoveryIndex(),"quiet recover");}
 private static void userAuthorityHoldBlocksImmediateOrdinaryCounterWrite(){ControlVolumeCurve curve=curve();NormalizerControlCoordinator c=new NormalizerControlCoordinator();c.onFrame(frame(0,2,2,curve,-20,-30,NormalizerControlCoordinator.VolumeObservation.UNCHANGED,VolumeWriteOrigin.NORMALIZATION,true,true,"exact",EngineCapabilities.SourceIdentityConfidence.EXACT));ControlCommand x=c.onFrame(frame(100,1,2,curve,-1,5,NormalizerControlCoordinator.VolumeObservation.USER,VolumeWriteOrigin.USER,true,true,"exact",EngineCapabilities.SourceIdentityConfidence.EXACT));eq(ControlCommand.Kind.NONE,x.kind(),"anti fight");yes(x.reason().contains("user_master"),"hold telemetry");}
 private static void coordinatorRepaysOwnedDebtWithUnknownSource(){ControlVolumeCurve curve=curve();NormalizerControlCoordinator c=new NormalizerControlCoordinator();c.onFrame(frame(0,5,5,curve,-20,-20,NormalizerControlCoordinator.VolumeObservation.UNCHANGED,VolumeWriteOrigin.NORMALIZATION,true,false,"no_exact_source",EngineCapabilities.SourceIdentityConfidence.UNKNOWN));c.onFrame(frame(100,5,4,curve,-20,-20,NormalizerControlCoordinator.VolumeObservation.APP_ACK,VolumeWriteOrigin.NORMALIZATION,true,false,"no_exact_source",EngineCapabilities.SourceIdentityConfidence.UNKNOWN));ControlCommand warm=c.onFrame(frame(200,4,4,curve,-20,-20,NormalizerControlCoordinator.VolumeObservation.UNCHANGED,VolumeWriteOrigin.NORMALIZATION,true,false,"no_exact_source",EngineCapabilities.SourceIdentityConfidence.UNKNOWN));eq(ControlCommand.Kind.NONE,warm.kind(),"warm");ControlCommand r=c.onFrame(frame(550,4,4,curve,-20,-20,NormalizerControlCoordinator.VolumeObservation.UNCHANGED,VolumeWriteOrigin.NORMALIZATION,true,false,"no_exact_source",EngineCapabilities.SourceIdentityConfidence.UNKNOWN));eq(ControlCommand.Kind.MEDIA_INDEX,r.kind(),"debt command");eq(5,r.mediaIndex(),"debt target");eq(ControlCommand.Provenance.DEBT_RECOVERY,r.provenance(),"provenance");}
 private static NormalizerControlCoordinator.Frame frame(long at,int prev,int cur,ControlVolumeCurve c,float peak,float program,NormalizerControlCoordinator.VolumeObservation o,VolumeWriteOrigin origin,boolean sourceControl,boolean positive,String policy,EngineCapabilities.SourceIdentityConfidence confidence){return new NormalizerControlCoordinator.Frame.Builder(at,prev,cur,c).rawPeakDbfs(peak).controlLoudnessDb(program).mediaGainDb(c.gainDbForIndex(cur)).captureReference(CaptureReferenceEstimator.Mode.PRE_VOLUME).hardPeakCeilingDbfs(-2).hardMediaCeilingIndex(5).rawProgramActive(true).effectivePolicy(policy,sourceControl,positive).sourceEvidence(confidence).playbackEndpoints(true,1).observation(o,origin).build();}
 private static ControlVolumeCurve curve(){return ControlVolumeCurve.fromVendorRaw(0,5,new float[]{-60,-45,-30,-20,-10,0});}
 private static void yes(boolean v,String m){if(!v)throw new AssertionError(m);}private static void no(boolean v,String m){if(v)throw new AssertionError(m);}private static void eq(Object e,Object a,String m){if(e==null?a!=null:!e.equals(a))throw new AssertionError(m+" expected="+e+" actual="+a);}private static void eq(int e,int a,String m){if(e!=a)throw new AssertionError(m+" expected="+e+" actual="+a);}
}
